### PR TITLE
BootLoader v2.19

### PR DESCRIPTION
**Pull request by DwaineGarden**
The newest BootLoader Bin File for RK3188

### CODE REVIEW

**Comment by DwaineGarden** [comment]
I tried out the bootloader v2.19 and it worked fine.   I have absolutely no idea what changes are in v2.19.  So for the moment, I just pushed the Bin file.  Did not change the scripts to use Bin file v2.19.

**Comment by DwaineGarden** [comment]
Been test this newer version for a couple of weeks.   I have not seen any issues with it.

Dwaine

**Comment by DwaineGarden** [comment]
I think we can pull this.  Been running for a while with no problems.

**Comment by DwaineGarden** [comment]
Nobody wants the 2.19 bootloader?

**Comment by red13dotnet** [comment]
I haven't been an active participant on here as of yet, but I'd like to see
a change log personally.  I am looking around to see what I can find.

**Comment by DwaineGarden** [comment]
I could not find a change log for bootloader 2.19 anywhere.    Been running it for a while.

**Comment by jamesgol** [comment]
Not sure how I missed this PR

**Pull request merged**
